### ISSUE TITLE
Problem on "Artisan Start Server" default host and port

### ISSUE THREAD

**Issue by alaminfirdows** [TheColorRed/vscode-laravel-artisan#48] opened 2019-10-10 08:26 UTC
When I try to start the laravel project by "Artisan Start Server" default host and port it produces an incompleted command.

Like ```php "{location}" serve --host='localhost --port='8000```

![image](https://user-images.githubusercontent.com/30468274/66551733-dd652e80-eb69-11e9-8e23-754f0ebcf82e.png)

**Comment by alaminfirdows** [comment] 2019-10-10 08:39
I've fixed it.
![image](https://user-images.githubusercontent.com/30468274/66552779-bd366f00-eb6b-11e9-82b8-ad2f0bc8c2c4.png)

**Comment by NariyasuHeseri** [comment] 2019-10-10 08:52
> I've fixed it.
> ![image](https://user-images.githubusercontent.com/30468274/66552779-bd366f00-eb6b-11e9-82b8-ad2f0bc8c2c4.png)

Great! Why not open a pull request?

**Comment by alaminfirdows** [comment] 2019-10-10 08:55
> > I've fixed it.
> > ![image](https://user-images.githubusercontent.com/30468274/66552779-bd366f00-eb6b-11e9-82b8-ad2f0bc8c2c4.png)
> 
> Great! Why not open a pull request?

I am going to create it. Thanks.

**Comment by TheColorRed** [comment] 2019-10-10 14:30
Duplicate of #47

**Closed by TheColorRed** 2019-10-10 14:30 UTC
